# Generated by Django 5.0.1 on 2024-02-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='ada', upload_to='upload/product/'),
            preserve_default=False,
        ),
    ]
