# Generated by Django 5.0.1 on 2024-02-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
