# Generated by Django 5.0.1 on 2024-03-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_remove_cartitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
