# Generated by Django 5.0.1 on 2024-02-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_accountverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountverification',
            old_name='idUser',
            new_name='user',
        ),
    ]
