# Generated by Django 5.0.1 on 2024-03-09 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 20, 16, 50, 723392, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 20, 16, 50, 723392, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 20, 16, 50, 724389, tzinfo=datetime.timezone.utc)),
        ),
    ]
