# Generated by Django 5.0.1 on 2024-04-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_alter_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
