# Generated by Django 5.0.1 on 2024-04-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unconfirm', 'Unconfirm'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered')], max_length=20),
        ),
    ]
