# Generated by Django 5.0.1 on 2024-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='image_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
