# Generated by Django 5.0.1 on 2024-04-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_alter_returnorder_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnorder',
            old_name='image_path',
            new_name='image',
        ),
    ]
