# Generated by Django 5.0.1 on 2024-04-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_rename_image_path_returnorder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.BigIntegerField(),
        ),
    ]
