# Generated by Django 5.0.1 on 2024-04-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_alter_order_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(default='ada', upload_to='images/'),
            preserve_default=False,
        ),
    ]
