# Generated by Django 5.0.1 on 2024-04-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_order_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
    ]
