# Generated by Django 5.0.1 on 2024-04-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_remove_returnorder_id_returnorder_id_return_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Received', 'Received')], default='Sent', max_length=20),
        ),
    ]
