# Generated by Django 5.0.1 on 2024-04-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='id',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='id_testimonial',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
