# Generated by Django 5.0.1 on 2024-04-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0019_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='denda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='foto_pengembalian',
            field=models.ImageField(blank=True, null=True, upload_to='return_photos'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_receipt_image_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
