# Generated by Django 5.0.1 on 2024-04-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0020_order_denda_returnorder_foto_pengembalian_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnorder',
            old_name='foto_pengembalian',
            new_name='photo_payment_fine',
        ),
        migrations.RemoveField(
            model_name='order',
            name='denda',
        ),
        migrations.AddField(
            model_name='order',
            name='fine',
            field=models.BigIntegerField(default=0),
        ),
    ]
