# Generated by Django 5.0.1 on 2024-05-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0021_rename_foto_pengembalian_returnorder_photo_payment_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnorder',
            name='photo_payment_fine',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_receipt_code',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
