# Generated by Django 5.0.1 on 2024-05-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0022_alter_returnorder_photo_payment_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Belun Terkonfirmasi', 'Belun Terkonfirmasi'), ('Terkonfirmasi', 'Terkonfirmasi'), ('Dikirim', 'Dikirim')], max_length=20),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('Terkirim', 'Terkirim'), ('Diterima', 'Diterima')], default='Terkirim', max_length=20),
        ),
    ]
